trafficmonitoring/task/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'task'

urlpatterns = [
    path('', views.index, name='index'),
    path('result/<int:task_id>', views.counting_result, name='result'),
    path('create_task', views.create_task, name='create_task'),
    path('mytask/', views.my_task, name='mytask'),
    path('edit_loop/<int:task_id>', views.edit_loop, name='edit_loop'),
    path('delete_loop/<int:loop_id>', views.delete_loop, name='delete_loop'),
    path('run_task/<int:task_id>', views.run_task, name='run_task'),
    path('modify_loop/<int:task_id>/<int:loop_id>', views.modify_loop, name='modify_loop'),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

trafficmonitoring/trafficmonitoring/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('task.urls')),
]

trafficmonitoring/user/urls.py
from django.urls import path, re_path
from . import views

app_name = 'user'

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout_view'),
]

trafficmonitoring/user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Account(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    img_profile = models.ImageField(upload_to = "uploads/", blank=True)
    role = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.user.username}"

trafficmonitoring/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from user.models import Account
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.

def signin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('task:index'))
        else:
            return render(request, 'user/signin.html', {
                'message': 'Invalid credentials.'
            })
    return render(request, 'user/signin.html')

def signup(request):
    if request.method == 'POST':
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirmpassword = request.POST.get('confirmpassword')

        # Check if the passwords and username is in correct format
        
        if password != confirmpassword and User.objects.filter(username=username).exists():
            message1 = 'Passwords do not match'
            message2 = 'Username already taken'
            return render(request, 'user/signup.html', {'message1': message1, 'message2': message2})
        
        if password != confirmpassword:
            message1 = 'Passwords do not match'
            return render(request, 'user/signup.html', {'message1': message1})

        if User.objects.filter(username=username).exists():
            message2 = 'Username already taken'
            return render(request, 'user/signup.html', {'message2': message2})

        # Create a new user account
        user = User.objects.create(username=username, email=email,
                     first_name=firstname, last_name=lastname)
        user.set_password(password)
        user.save()

        Account.objects.create(user=user)

        return HttpResponseRedirect(reverse('user:signin',))
    else:
        return render(request, 'user/signup.html')

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('user:signin'))
    

trafficmonitoring/user/templates/user/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://example.com/fontawesome/v6.3.0/js/fontawesome.js" data-auto-replace-svg="nest"></script>
    <script src="https://example.com/fontawesome/v6.3.0/js/solid.js"></script>
    <script src="https://example.com/fontawesome/v6.3.0/js/brands.js"></script>
    <title>Traffic Mornitoring</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'user/styles.css' %}" />
    <script src="{% static 'user/functions.js' %}"></script>
    
</head>

    {% block body %}
    {% endblock %}

</html>

trafficmonitoring/user/templates/user/signin.html
{% extends 'user/layout.html' %}
{% block body %}
<body class="h-100">
  <br>
  <section>
    <div class="text-center mt-4">
      <p class="header">Sign In</p>
      <div class="container w-50">
        <form class="mt-5" action="{% url 'user:signin' %}" method="POST">
          {% csrf_token %} 
          <div class="form-row text-left">
            <label>Username</label>
            <input type="text" class="form-control" name="username">
            <br>
            <label>Password</label>
            <input type="password" class="form-control" name="password">
            {% if message %}
            <div style="color: red">{{ message }}</div>
            {% endif %}
          </div>
          <br>
          <button type="submit" class="btn">Sign In</button>
          <br>
          <a href="{% url 'user:signup' %}" >Don't have an account?</a>
        </form> 
      </div>
    </div>
  </section>
</body>
{% endblock %}

trafficmonitoring/user/templates/user/signup.html
{% extends 'user/layout.html' %}
{% block body %}

<body class="h-100">
<br>
<section>
    <div class="text-center mt-4">
      <p class="header">Sign Up</p>
      <div class="container w-50">
        <form class="mt-5" action="{% url 'user:signup' %}" method="POST">
          {% csrf_token %}
          <div class="form-row text-center" style="display: flex; justify-content: center;">
          </div>
          <br>
          <div class="form-row text-left">
            <div class="form-group col-md-6">
              <label>First Name</label>
              <input required type="text" class="form-control" id="firstname" name="firstname">
            </div>
            <div class="form-group col-md-6">
              <label>Last Name</label>
              <input required type="text" class="form-control" id="lastname" name="lastname">
            </div>
          </div>
          <div class="form-row text-left">
            <div class="form-group col-md-6">
              <label>Username</label>
              <input type="text" class="form-control" id="username" name="username">
              {% if message2 %}
              <div style="color: red">{{ message2 }}</div>
              {% endif %}
            </div>
            <div class="form-group col-md-6">
              <label>Role</label>
              <select name="role" class="form-control" required>
                <option value="normal">Normal User</option>
                <option value="officer">Officer</option>
              </select>
            </div>
          </div>
          <div class="form-group text-left">
              <label>Email</label>
              <input required type="email" class="form-control" id="email" name="email">
          </div>
          <div class="form-row text-left">
            <div class="form-group col-md-6">
              <label>Password</label>
              <input type="password" class="form-control" id="password" name="password">
            </div>
            <div class="form-group col-md-6">
              <label>Confirm Password</label>
              <input type="password" class="form-control" id="confirmpassword" name="confirmpassword">
              {% if message1 %}
              <div style="color: red">{{ message1 }}</div>
              {% endif %}
            </div>
          </div>
          <button type="submit" class="btn">Sign Up</button>
          <br>
          <a href="{% url 'user:signin' %}" >Already have an account?</a>
          
        </form> 
      </div>
    </div>
  </section>
  <br><br><br>
</body>
{% endblock %}