trafficmonitoring/task/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'task'

urlpatterns = [
    path('', views.index, name='index'),
    path('result/<int:task_id>', views.counting_result, name='result'),
    path('create_task', views.create_task, name='create_task'),
    path('mytask/', views.my_task, name='mytask'),
    path('edit_loop/<int:task_id>', views.edit_loop, name='edit_loop'),
    path('delete_loop/<int:loop_id>', views.delete_loop, name='delete_loop'),
    path('run_task/<int:task_id>', views.run_task, name='run_task'),
    path('modify_loop/<int:task_id>/<int:loop_id>', views.modify_loop, name='modify_loop'),

] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

trafficmonitoring/trafficmonitoring/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('task.urls')),
]

trafficmonitoring/user/urls.py
from django.urls import path, re_path
from . import views

app_name = 'user'

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout_view, name='logout_view'),
]

trafficmonitoring/task/models.py
from django.db import models
from user.models import Account
# Create your models here.
    
class Task(models.Model):
    STATUS_PENDING = 'PENDING'
    STATUS_START = 'START'
    STATUS_ERROR = 'ERROR'
    STATUS_SUCCESS = 'SUCCESS'

    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, default="")
    date_time = models.DateTimeField('date_time', auto_now_add=True)
    date_time_modify = models.CharField(max_length=100, default="")
    date_time_upload = models.CharField(max_length=100, default="")
    location = models.CharField(max_length=100, default="")
    description = models.CharField(max_length=256, default="")
    weather = models.CharField(max_length=20, default="", blank=True)
    status = models.CharField(max_length=15, default="")

    def __str__(self):
        return f"{self.name}"
    
class Input(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    video = models.FileField(upload_to = 'uploads/', blank=True)
    sample_img = models.FileField(upload_to = 'uploads/', blank=True)
    fig_img = models.FileField(upload_to = 'uploads/', blank=True)

    def __str__(self):
        return f"{self.video}"
    
class Result(models.Model):
    input = models.ForeignKey(Input, on_delete=models.CASCADE)
    video = models.FileField(upload_to = 'uploads/', blank=True)

    def __str__(self):
        return f"{self.video}"

class Loop(models.Model):
    input = models.ForeignKey(Input, on_delete=models.CASCADE)
    loop_name = models.CharField(max_length=100, blank=True)
    x = models.IntegerField(blank=True)
    y = models.IntegerField(blank=True)
    width = models.IntegerField(blank=True)
    height = models.IntegerField(blank=True)
    angle = models.IntegerField(blank=True)
    direction = models.IntegerField(blank=True)

    def __str__(self):
        return f"{self.loop_name}"
class Car(models.Model):
    loop = models.ForeignKey(Loop, on_delete=models.CASCADE)
    car_total = models.IntegerField(default=0)
    car_type = models.CharField(max_length=20)
    direction = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.car_total}"

class TotalCar(models.Model):
    result = models.ForeignKey(Result, on_delete=models.CASCADE)
    type = models.CharField(max_length=20)
    total = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.type}"

trafficmonitoring/task/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from .models import Task, Input, Result, Loop, Car, TotalCar
from django.contrib.auth.models import User
from user.models import Account
from .task import detect_track
from opt import OptJson
import cv2
import os
import matplotlib.pyplot as plt
import math
from .loop import Loops as set_loop

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('user:signin'))
    
    task = Task.objects.all().order_by('-date_time')

    list_detail_task = {}
    for t in task:
        total = 0
        if t.status != "SUCCESS":
            continue
        try:
            input = Input.objects.get(task=t)
            result = Result.objects.get(input=input)
            totalCar = TotalCar.objects.filter(result=result)
            for car in totalCar:
                total += car.total
        except:
            pass
        list_detail_task[t] = {'input':input, 'total': total}

    return render(request, 'task/index.html', {
        # 'task': task,
        'list_detail_task': list_detail_task
    })

def counting_result(request, task_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('user:signin'))
    
    task = Task.objects.get(id=task_id)
    input = Input.objects.get(task=task)
    result = Result.objects.get(input=input)
    loop = Loop.objects.filter(input=input)
    totalcar = TotalCar.objects.filter(result=result)
    list_totalcar = {}
    list_index = {}
    index = 1
    for t in totalcar:
        list_totalcar[t.type] = t.total

    for l in loop:
        list_index[l.id] = index
        index +=1 

    if request.method == 'POST':
        loop_id = request.POST['loop_id']
        loop_detail = Loop.objects.get(id=int(loop_id))
        car = Car.objects.filter(loop=loop_detail)

        list_left = {}
        list_right = {}
        list_straight = {}
        for c in car:
            if(c.direction == 'LEFT'):
                list_left[c.car_type] = c.car_total
            elif(c.direction == 'RIGHT'):
                list_right[c.car_type] = c.car_total
            elif(c.direction == 'STRAIGHT'):
                list_straight[c.car_type] = c.car_total
        return render(request, 'task/result.html', {
            'task': task,
            'result': result,
            'loop': loop,
            'totalcar': totalcar,
            'list_totalcar': list_totalcar,
            'loop_detail': loop_detail,
            'list_left': list_left,
            'list_right': list_right,
            'list_straight': list_straight,
            'list_index': list_index
        })
    return render(request, 'task/result.html', {
        'task': task,
        'result': result,
        'loop': loop,
        'totalcar': totalcar,
        'list_totalcar': list_totalcar,
        'list_index': list_index
    })
    
def create_task(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('user:signin'))
    
    if request.method == 'POST':
        user = User.objects.get(username=request.user.username)
        account = Account.objects.get(user=user)
        name = request.POST['name']
        location = request.POST['location']
        description = request.POST['description']  
        weather = request.POST['weather']  

        task = Task.objects.create(account=account, name=name, location=location, weather=weather,
                                    description=description, status=Task.STATUS_PENDING )
        
        video = request.FILES['video']
        input = Input.objects.create(task=task, video=video)
        cam = cv2.VideoCapture(input.video.path)
        ret, frame = cam.read()
        if ret:
            name = str(input.video.name.split('.')[0]) + ".png"
            cv2.imwrite("./media/frame/" + name, frame)
            input.sample_img = "./frame/" + name
            pic = plt.imread("./media/frame/" + name)
            fig = plt.figure()
            ax = fig.subplots()
            ax.imshow(pic)
            plt.savefig("./media/fig/" + name)
            input.fig_img = "./fig/" + name
            input.save()

        return HttpResponseRedirect(reverse('task:edit_loop', args=(task.id,)))
    
    return render(request, 'task/create_task.html')

def edit_loop(request, task_id):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('user:signin'))
    
    task = Task.objects.get(id=task_id)
    input = Input.objects.get(task=task)
    if request.method == "POST":
        loop_name = request.POST["loop_name"]
        x = int(request.POST["x"])
        y = int(request.POST["y"])
        width = int(request.POST["width"])
        height = int(request.POST["height"])
        angle = int(request.POST["angle"])
        direction = int(request.POST["direction"])

        loop = Loop.objects.create(input=input, loop_name=loop_name, x=x, y=y,
                                   width=width, height=height, angle=angle, direction=direction)
        set_loop(input).draw_loop()
    all_loop = Loop.objects.filter(input=input)
    return render(request, 'task/edit_loop.html', {
        "task": task,
        "input": input,
        "all_loop": all_loop,
    })

def delete_loop(request, loop_id):
    try:
        loop = Loop.objects.get(id=loop_id)
    except:
        return HttpResponseRedirect(reverse('task:index'))
    
    input = loop.input

    loop.delete()
    set_loop(input).draw_loop()
    return HttpResponseRedirect(reverse('task:edit_loop', args=(input.task.id,)))

def run_task(request, task_id):
    task = Task.objects.get(id=task_id)
    input = Input.objects.get(task=task)
    opt = OptJson
    opt['source'] = input.video.path
    opt['project'] = './media/uploads/' + str(request.user.username) + '/' + str(task.id)
    opt['loop'] = set_loop(input).create_loop(Loop.objects.filter(input=input))

    task.status=Task.STATUS_PENDING
    task.save()

    detect_track.delay(opt, task.id)
    return HttpResponseRedirect(reverse('task:mytask'))


def my_task(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('user:signin'))
    
    user = User.objects.get(username=request.user.username)
    account = Account.objects.get(user=user)
    task = Task.objects.filter(account=account).order_by('-date_time')

    return render(request, 'task/mytask.html', {
        'task': task,
    })

def modify_loop(request, task_id, loop_id):
    task = Task.objects.get(id=task_id)
    input = Input.objects.get(task=task)
    loop = Loop.objects.get(id=loop_id)
    if request.method == "POST":
        loop.loop_name = request.POST["loop_name"]
        loop.x = int(request.POST["x"])
        loop.y = int(request.POST["y"])
        loop.width = int(request.POST["width"])
        loop.height = int(request.POST["height"])
        loop.angle = int(request.POST["angle"])
        loop.direction = int(request.POST["direction"])
        loop.save()
        set_loop(input).draw_loop()
        return HttpResponseRedirect(reverse('task:edit_loop', args=(task.id,)))

    return render(request, 'task/modify_loop.html',{
        'task': task,
        'input': input,
        "loop":loop
    })

trafficmonitoring/task/templates/task/create_task.html
{% extends 'task/layout.html' %}

{% block body %}
<body class="h-100">
        <section>
            <div class="text-center mt-4">
                <h1>New Task</h1>
                <div class="container w-50">
                    <form class="mt-5" action="{% url 'task:create_task' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row text-left">
                            <div class="form-group col-md-6">
                                <label>Name</label>
                                <input type="text" name="name" class="form-control" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label>Date and Time</label>
                                <input type="text" name="datetime" class="form-control" required>
                            </div>
                        </div>

                        <div class="form-row text-left">
                            <div class="form-group col-md-6">
                                <label>Location</label>
                                <input type="text" name="location" class="form-control" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label>Upload file</label>
                                <input type="file" name="video" class="form-control" required>
                            </div>
                        </div>

                        <div class="form-group text-left">
                            <label>Weather</label>
                            <input type="text" name="weather" class="form-control" required>
                        </div>

                        <div class="form-group text-left">
                            <label>Description</label>
                            <textarea row="4" col="20" name="description" class="form-control"> </textarea>
                        </div>
                        <br>
                        <button type="submit" class="btn">New loop</button>
                        {% comment %} <button class="btn">Present</button> {% endcomment %}
                        <br><br><br>
                    </from>
                </div>
            </div>
        </section>

</body>
{% endblock %}

trafficmonitoring/task/templates/task/edit_loop.html
{% extends 'task/layout.html' %}

{% block body %}
<body class="h-100">
        <section>
            <div class="text-center mt-4">
                <h1>Set Loop</h1>
                <div class="container w-50">
                    <form class="mt-5" action="{% url 'task:edit_loop' task.id %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-row text-center" style="display: flex; justify-content: center;">
                            <div class="form-group">
                                <img src="/media/{{input.fig_img}}">
                            </div>
                        </div>
                        
                        <div class="form-group text-left">
                            <label>Loop Name</label>
                            <input type="text" name="loop_name" class="form-control" required>
                        </div>
                        <div class="form-row text-left">
                            <div class="form-group col-md-6">
                                <label>x</label>
                                <input type="text" name="x" class="form-control" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label>y</label>
                                <input type="text" name="y" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-row text-left">
                            <div class="form-group col-md-6">
                                <label>width</label>
                                <input type="text" name="width" class="form-control" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label>height</label>
                                <input type="text" name="height" class="form-control" required>
                            </div>
                        </div>
                        <div class="form-row text-left">
                            <div class="form-group col-md-6">
                                <label>Angle</label>
                                <input type="text" name="angle" class="form-control" required>
                            </div>
                            <div class="form-group col-md-6">
                                <label>Direction</label>
                                <select name="direction" class="form-control" required>
                                    <option value="" selected disabled hidden>Choose here</option>
                                    <option value="1">↖</option>
                                    <option value="2">↑</option>
                                    <option value="3">↗</option>
                                    <option value="4">→</option>
                                    <option value="5">↘</option>
                                    <option value="6">↓</option>
                                    <option value="7">↙</option>
                                    <option value="8">←</option>
                                </select>
                            </div>
                        </div>  
                        <button type="submit" class="btn">Add Loop</button>
                    </from>
                </div>
            </div>
        </section>
        <section>
            <div class="text-center mt-4">
                <div class="container w-50">
                    <table>
                        <tr>
                            <th>Loop Name</th>
                            <th>Loop Setting</th>
                            <th>Delete</th>
                            <th>Modify</th>
                        </tr>
                        {% for loop in all_loop %}
                            <tr>
                                <td>{{loop.loop_name}}</td>
                                <td>x:{{loop.x}} y:{{loop.y}} width:{{loop.width}} height:{{loop.height}} angle:{{loop.angle}} direction:{{loop.direction}}</td>
                                <td><a href="{% url 'task:delete_loop' loop.id %}">delete</a></td>
                                <td><a href="{% url 'task:modify_loop' task.id loop.id %}">modify</a></td>
                            </tr>
                        {% endfor %}
                    </table>
                    <br>
                    <a class="btn" href="{% url 'task:run_task' task.id%}">run</a>    
                </div>
            </div>
            
        </section>

</body>
{% endblock %}

trafficmonitoring/task/templates/task/home.html
{% extends 'task/layout.html' %}
{% block body %}
<body>
    <header>
        <h1>Traffic Monitoring Site</h1>
    </header>

    <main>
        
    </main>
</body>
{% endblock %}

trafficmonitoring/task/templates/task/index.html
{% extends 'task/layout.html' %}
{% block body %}
<body id = "index">
    <header>
        <h1>Traffic Monitoring Site</h1>
    </header>
    <main>
        {% for task, input in list_detail_task.items %}
            <a class = 'index_task' href="{% url 'task:result' task.id %}">
                <div class="blockindex grid-container">
                    <img src='/media/{{input.input.sample_img}}' width=250px height=150px>

                    <aside class="grid-aside">
                        <div>
                            Name: {{ task.name }}<br>
                            Location: {{ task.location}}<br>
                            Total vehicles: {{input.total}}<br>
                            Weather: {{task.weather}}<br>
                            Time: {{ task.date_time }}<br>
                            Create by: {{ task.account }}<br>
                        </div>
                    </aside>
                </div>
            </a>
            <br>
        {%endfor%}
    </main>
    
</body>
{% endblock %}

trafficmonitoring/task/templates/task/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://example.com/fontawesome/v6.3.0/js/fontawesome.js" data-auto-replace-svg="nest"></script>
    <script src="https://example.com/fontawesome/v6.3.0/js/solid.js"></script>
    <script src="https://example.com/fontawesome/v6.3.0/js/brands.js"></script>
    <title>Traffic Mornitoring</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'task/styles.css' %}" />
    <script src="{% static 'user/functions.js' %}"></script>

    <style>
        body {
            font-family: Arial, sans-serif,'Poppins';
        }

        nav {
            background-color: #cec387;
        }

        .search {
            margin-top: 10px;
            margin-bottom: 10px;
            padding: 10px 16px;
        }

        .rightbutton {
            float: right;
            margin: 20px;
        }

        .blockbody {
            display: block;
            margin: auto;
            width: 850px;
        }


        .blockindex{
            display: block;
            margin: auto;
            background-color:#d9d9d9;
            width: 700px;
            height: auto;
            border-radius: 5px;
            padding: 10px;
        }

        .grid-container {
            display: grid;
            grid-template-columns: 1fr 2fr;
            grid-template-rows: auto auto;
        }

        .grid-main {
            padding: 10px;
            grid-column: 1/2;
            grid-row: 1/2;
        }

        .grid-aside {
            padding-left: 20px;
            text-align: left;
            grid-column: 2/3;
            grid-row: 1/2;
        }

        table, td, th {  
            border: 1px solid rgb(152, 152, 152);
            text-align: left;
        }
        
        table {
            border-collapse: collapse;
            background-color: #b2dad4;
        }
        
        th, td {
            padding: 15px;
        }

        nav{
            background-color: #CEC387;
        }

        .search{
            margin-top: 10px;
            margin-bottom: 10px;
            padding: 10px 16px;
            margin-left: 30px;
            border: 1px solid gray;
            text-align: left;
            padding: 15px;
        }
        
        th {
            background-color: #b2dad4;
        }

        td {
            background-color: #d5e3e0;
        }

        .btn{
            font-size: 15px;
            color: white;
            background-color: #8797CE;
            width: 130px;
            height: 40px;
            border-radius: 12px;
            border: none;
            margin: 12px;
        }

        .btn:hover {
            background-color: rgb(80, 87, 160);
            transition-delay: 0.04s;
        }

        h1{
            margin-top: 10px;
            text-align: center;
        }

        .center{
            margin-left: auto;
            margin-right: auto;
        }

        .centerb{
            text-align: center;
        }

        .b-col {
            background-color: #FFFFFF;
        }

        .mg {
            margin: auto;
            max-width: 60%;
        }
        .material-symbols-outlined {
            color:black;
            font-size:30px;
        }
        .nav-item{
            font-weight: bold;
        }
        .nav-item:hover{
            text-decoration: underline;
            transition-delay: 0.2s;
        }

        video {
            margin: 10px;
        }
        
        input::file-selector-button {
            color: white;
            background-color: #8797CE;
            width: auto;
            height: 28px;
            border-radius: 4px;
            border: none;
            margin-bottom: 3px;
            cursor: pointer;
        }
        
        .index_task:hover{
            text-decoration: none;
            color: black;
        }
        .index_task{
            color:black;
        }
        </style>

        
            
</head>
<nav class="navbar navbar-expand-lg bar">
    <a href="{% url 'task:index' %}">
        <span style="padding:5px; margin-right:15px; text-decoration:none; color:black; font-size:22.5px;">
            TrafficMonitoring
        </span>
    </a>
    <button class="navbar-toggler b-col" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" 
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">
            <span class="material-symbols-outlined">expand_more</span>
        </span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        {% comment %} <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        </form> {% endcomment %}
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link text-dark mx-3 align-middle" href="{% url 'task:create_task' %}">Create Task</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark mx-3 align-middle" href="{% url 'task:mytask' %}">My Task</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-dark mx-3 align-middle" href="{% url 'user:logout_view' %}">Logout</a>
        </li>
      </ul>
    </div>
</nav>
    {% block body %}
    {% endblock %}

</html>

trafficmonitoring/task/templates/task/result.html
{% extends 'task/layout.html' %}
{% block body %}
<body>
    <div class="text-center">
        <h1>Counting Result</h1>
    </div>
    <main>
        <div class = "blockbody grid-container">
            <main class="grid-main">
                <video width="320" height="240" controls>
                    <source src="/media/{{ result.video }}" type="video/mp4">
                    Your browser does not support HTML video.
                </video>

                <div>
                    <p>Time: {{task.date_time}}</p>
                </div>

                <div>
                    <p>Weather: {{task.weather}}</p>
                </div>

                <div>
                    <p>Created By: {{task.account.user.username}}</p>
                </div>

                
                <div></div>

                <footer>
                    <a href="{% url 'task:mytask' %}"><button class = "btn">Back</button></a>
                    {% if task.account.user.username == user.username %}
                        <a href="{% url 'task:edit_loop' task.id %}"><button class = "btn">Edit Loop</button></a>
                    {% endif %}
                </footer>
            </main>

            <aside class="grid-aside">
                <div>
                    <h2>Total Vehicles: </h2>

                    <table>
                        <tr>
                            <th>Car: </th>
                            <td>{{list_totalcar.car}}</td>
                            <th>Truck: </th>
                            <td>{{list_totalcar.truck}}</td>
                            <th>Bike: </th>
                            <td>{{list_totalcar.motorcycle}}</td>
                        </tr>
                    </table>
                </div>

                <div>
                    <h2>Loop detail: </h2>

                    <table>
                        <tr>
                            <th>No.</th>
                            <th>Loop Name</th>
                            <th>รายละเอียด</th>
                        </tr>
                            {% for i in loop %}
                                <form method="post" action="{% url 'task:result' task.id %}">
                                    {% csrf_token %}
                                    <tr>
                                        <td>{{i.id}} </td>
                                        <td>{{i.loop_name}}</td>
                                        <td><button style ="margin:0px" class = "btn" type="submit" name = "loop_id" value = "{{i.id}}">detail</button></td>
                                    </tr>
                                </form> 
                            {%endfor%}
                    </table>
                    <p></p>
                    {% comment %} <a href="{% url 'task:delete_loop' loop.id %}"><button class = "btn">Delete Loop</button></a> {% endcomment %}
                </div>
                <p></p>
                {%if list_left %}
                    <div>
                        <p>Loop Name: {{loop_detail.loop_name}}</p>
                        <table>
                            <tr>
                                <th>Direction/Type</th>
                                <th>Car</th>
                                <th>Truck</th>
                                <th>Bike</th>
                            </tr>
                            <tr>
                                <th>Left</th>
                                <td>{{list_left.car}}</td>
                                <td>{{list_left.truck}}</td>
                                <td>{{list_left.motorcycle}}</td>
                            </tr>
                            <tr>
                                <th>Right</th>
                                <td>{{list_right.car}}</td>
                                <td>{{list_right.truck}}</td>
                                <td>{{list_right.motorcycle}}</td>
                            </tr>
                            <tr>
                                <th>Straight</th>
                                <td>{{list_straight.car}}</td>
                                <td>{{list_straight.truck}}</td>
                                <td>{{list_straight.motorcycle}}</td>
                            </tr>
                        </table>
                    </div>
                {%endif%}
            </aside>
        </div>
    </main>
</body>
{% endblock %}